### ISSUE TITLE
Tray icon doesnt respond

### ISSUE THREAD

**Issue by wennaspeedy** [lisiur/ChatWizard#42]
Tray icon shows after start up, but it doesnt respond to click. Tray also shows multiple times after multiple run.

![image](https://user-images.githubusercontent.com/10447994/230038300-5bce2986-8c0f-474a-8483-5832ec1e8241.png)

**Comment by lisiur** [comment]
When the window is closed or minimized, clicking on this icon will display the window. This is currently the only function of this icon, so when you say that clicking it has no response, does that mean that this function is also not working?

I shall fix the issue pertaining to the display of multiple windows in the upcoming version.

**Comment by wennaspeedy** [comment]
![image](https://user-images.githubusercontent.com/10447994/230092350-994c600b-373a-4793-86c1-101b7de09a72.png)

**Comment by yixiaip** [comment]
I am the same, this situation also occurs after minimizing or closing multiple times.

**Comment by lisiur** [comment]
> I am the same, this situation also occurs after minimizing or closing multiple times.
> 
> 
> 
> 
> 
> 

what's your platform and what's the version of the app you are using？

**Comment by lisiur** [comment]
Based on my testing on the Windows machine, I have observed that upon clicking on the close button, the window can always be restored through the tray icon. However, if it is minimized, restoring the window through the tray icon is not possible. Can you please confirm this?

**Comment by wennaspeedy** [comment]
I am using ubuntu based POPOS with Gnome DE 42.5 . App version 0.47.

After clicking close button, window dissappear and cant be restored trought the tray icon. Tray icon doesnt do anything.

**Comment by wennaspeedy** [comment]
Wait... After installing v 0.50 problem seems to be solved...

**Comment by wennaspeedy** [comment]
![image](https://user-images.githubusercontent.com/10447994/230286635-3d677607-8652-4275-bae9-3df2382e9cc7.png)

**Comment by lisiur** [comment]
> After installing v 0.50 problem seems to be solved... But always display "Show". It should display show and hide in my opinion.

I don‘t think it will be very effective. On the one hand, you can simply click the minimize or close button to hide the application, or even activate other applications to cover it. Therefore, personally, I do not believe it is necessary to add the "hide" logic in the tray icon. What do you think?

**Comment by wennaspeedy** [comment]
It is not necessary, but easy to implement ;)
