### ISSUE TITLE
dialog display problem

### ISSUE THREAD

**Issue by vvanglro** [lisiur/ChatWizard#50]
**Describe the bug**
The words we sent should be on the right?

**Screenshots**
![image](https://github.com/lisiur/ChatWizard/assets/43594924/bf8a6361-35aa-43fb-8109-b15f51d587d9)

**App Info:** 
Copy from app about:
 - App Version: 0.2.1
 - Platform: darwin
 - OS Type: Darwin
 - OS Version: 13.4.0
 - OS Arch: aarch64

**Comment by lisiur** [comment]
The left alignment of both the user's and assistant's messages has been deliberate since v0.1.0. This layout allows for optimal use of space, particularly in cases where a code block is present.

**Comment by vvanglro** [comment]
Ok, I get it.
