### ISSUE TITLE
Software resolution

### ISSUE THREAD

**Issue by yixiaip** [lisiur/ChatWizard#51]
Give a suggestion that when the screen resolution changes, the software should be able to respond with a responsive change in accordance with the screen resolution.

**Comment by lisiur** [comment]
On my Mac M1, this software can automatically adjust based on changes in resolution. What operating system are you using? Could you please use a screenshot to further illustrate this issue?

**Comment by lisiur** [comment]
Given the absence of subsequent responses, we shall temporarily close this issue. Feel free to reopen it if further feedback arises.
