### ISSUE TITLE
支持代码块高亮渲染和一键复制

### ISSUE THREAD

**Issue by normal-coder** [lisiur/ChatWizard#52]
**Is your feature request related to a problem? Please describe.**

无法高亮查看代码块并快速选择复制

**Describe the solution you'd like**

支持代码块高亮渲染和一键复制

**Describe alternatives you've considered**

暂无，可考虑参考如下：

**Additional context**

<img width="1082" alt="image" src="https://github.com/lisiur/ChatWizard/assets/6902432/d7bd9d96-1238-48f0-b710-0bd93dae8520">

**Comment by lisiur** [comment]
代码高亮应该是支持的，方便告知没有高亮的代码语言吗，或者贴出没有代码高亮的相关截图吗

**Comment by normal-coder** [comment]
目前是自己输入的部分没有渲染。

<img width="423" alt="image" src="https://github.com/lisiur/ChatWizard/assets/6902432/31917550-01d4-49ef-9f83-aa7dbe603f78">

**Comment by lisiur** [comment]
1. 用户输入的部分确实没有使用 markdown 渲染，后面会考虑加入这个功能。
2. 复制代码块的功能也会在下一个版本提供。

**Comment by normal-coder** [comment]
> 1. 用户输入的部分确实没有使用 markdown 渲染，后面会考虑加入这个功能。
> 2. 复制代码块的功能也会在下一个版本提供。

目前复制代码块和复制全文的边界不太清晰，可以考虑给整个内容块禁用文本选择（`user-select:none`）。毕竟已经提供了复制全文的功能了。

**Comment by lisiur** [comment]
这似乎不是很妥当，有些人可能只想复制部分内容

**Comment by normal-coder** [comment]
> 这似乎不是很妥当，有些人可能只想复制部分内容

目前代码块的选择会跨出。甚至会选中到标题（可能这些位置处理下会更好些）
