### ISSUE TITLE
Waiting for a response under macOS will cause serious window freezes

### ISSUE THREAD

**Issue by normal-coder** [lisiur/ChatWizard#55]
**Describe the bug**

Waiting for a response under macOS will cause serious window freezes

**To Reproduce**

Enter a question in macOS. In the process of responding to output results, the window will freeze and cannot perform any operations (including switching Tab, input, clicking the "Stop Responding" button, and moving the window)

**Expected behavior**

Response interface output does not affect normal windows and interactive operations.

**Screenshots**

**App Info:** 

Copy from app about:
 - App Version: Version 0.2.1 (20230515.062942)
 - Platform: macOS
 - OS Type: Darwin
 - OS Version: 13.4.1 (22F82)
 - OS Arch: Intel

**Additional context**

None

**Comment by lisiur** [comment]
I am unable to replicate the issue on my machine (M1). Furthermore, I do not possess an Intel machine at my disposal. If others encounter the same problem, I will diligently investigate it.
