### ISSUE TITLE
Anyone has success with localAI?

### ISSUE THREAD

**Issue by mounta11n** [lisiur/ChatWizard#56]
**Describe the bug**
ChatWizard does communicate with LocalAI, but a response is still not appearing.

**To Reproduce**
1. Start localAI
2. Start ChatWizard
3. In ChatWizard configure localAI as a forward URL like for example `http://127.0.0.1:8080`
4. In ChatWizard edit the models list and add a name of a model that is inside localAI's models folder (with extension, for example `WizardLM_Uncen-7B-q5K.bin`)
5. Start a new chat and choose the local model

**Expected behavior**
In your terminal window, where localAI is running, you should see that it correctly starts loading the model. But a response will never arrive at ChatWizard

**Screenshots**
![Imgur](https://i.imgur.com/2EV8c3G.jpg)

**App Info:** 
Copy from app about:
 - App Version: [Version 0.4.0 (20230709.113618)]
 - Platform: [darwin]
 - OS Type: [Darwin]
 - OS Version: [13.2 (22D49)]
 - OS Arch: [x64]

Would be cool if anyone has figured out what the problem is and how to solve it.

**Comment by lisiur** [comment]
Are you using this one? https://github.com/go-skynet/LocalAI

**Comment by mounta11n** [comment]
Oh wow, that was incredibly fast! I've installed 0.4.1 and it is working like a charm now. Thanks very much : )
