### ISSUE TITLE
web version ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [lisiur/ChatWizard#57]
Can there be a web version of this interface that someone can host locally ?

**Comment by lisiur** [comment]
A web service has already been integrated.

<img width="860" alt="image" src="https://github.com/lisiur/ChatWizard/assets/15188817/bc89940e-e868-4e89-bd2c-0c8bd8867710">

**Comment by MohamedAliRashad** [comment]
@lisiur Can it be inferred without opening the GUI (Using the command line) ?

**Comment by lisiur** [comment]
Unfortunately, it is not currently possible. However, if it is your desire, I can offer a self-contained web server binary in the next version.

**Comment by MohamedAliRashad** [comment]
@lisiur This will be amazing. (Thanks in advance)

**Comment by lisiur** [comment]
Done! Check this https://github.com/lisiur/ChatWizard#server

**Comment by MohamedAliRashad** [comment]
@lisiur How to run it (the linux version) ?

**Comment by lisiur** [comment]
```bash
mv chat-wizard-server_x86_64-unknown-linux-gnu chat-wizard-server
chmod +x chat-wizard-server
./chat-wizard-server -p [port]
```
