### ISSUE TITLE
[Feature]: Allows to set the application home page as the "Chat" window, or set it as the default value

### ISSUE THREAD

**Issue by normal-coder** [lisiur/ChatWizard#60]
### Is your feature request related to a problem? Please describe.

For most desktop ChatGPT users, customizing the prompt or quickly switching the context of the conversation (switching between different conversations) is a strong appeal. 

By default, the application uses a non-important entry (casual chat) as the home page, so that users will encounter the problem of switching every time they come in. This drastically degrades the experience.

### Describe the solution you'd like

Set the default session window to "Chat" as default

### Describe alternatives you've considered

- Provide setting items, allowing users to set the default window Tab to open.
- or set the default session window to "Chat" as default

### Additional context

None

**Comment by lisiur** [comment]
That's a great suggestion. I'll add a configuration option to set the default page to open.

If you don't know, you can usually quickly switch the prompt by using a backslash(English input method).

<img width="860" alt="image" src="https://github.com/lisiur/ChatWizard/assets/15188817/c63a7ce6-a3d2-4ebb-b8dd-2f6c01550ab9">

**Comment by normal-coder** [comment]
> That's a great suggestion. I'll add a configuration option to set the default page to open.
> 
> If you don't know, you can usually quickly switch the prompt by using a backslash(English input method).
> 
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/15188817/256958368-c63a7ce6-a3d2-4ebb-b8dd-2f6c01550ab9.png">

Of course, I use this option frequently, but my stronger appeal is to separate topics of different content into different conversations (you know, we often need to switch back and forth between multiple things at the same time. Conversations with different content need Split in order to keep the context will not affect the analysis and accuracy of GPT)
