### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by drewdrew21b** [lisiur/ChatWizard#61]
It would be great if a container solution was offered so this could be easily used in conjunction with the localai container offering. This would simplify the required configurations even further than the current offerings.

**Comment by lisiur** [comment]
I'm not quite familiar with container technology. If anyone else knows about it, PR is welcome.

**Comment by xyana** [comment]
I could help out on this but where does ChatWizard place its configuration files? All I'm seeing is files in the .cache directory. (ubuntu). Or is that all that would need persistent storage?

**Comment by lisiur** [comment]
> I could help out on this but where does ChatWizard place its configuration files? All I'm seeing is files in the .cache directory. (ubuntu). Or is that all that would need persistent storage?

There is only one configuration file which located at `$HOME/.config/chat-wizard/chat-wizard.db` (linux)

**Comment by xyana** [comment]
I have it in `~/.local/share/chat-wizard ` Contains the following files: `chat-wizard.db  deviceidhashsalts  hsts-storage.sqlite  storage` Is this correct of should this be in .config?  Is this in some way configurable?

In any case this should be on a volume as well as the .cache dir. I suspect the plugins as well. Where are those stored?

**Comment by lisiur** [comment]
Sorry, I might have made a mistake. On Linux, the configuration file should really be in `$XDG_DATA_HOME/chat-wizard` or `$HOME/.local/share/chat-wizard`. But as far as I know, there should only be one chat-wizard.db file needed (the plugins are also stored in this file). At least on my Mac, there's just one file.

**Comment by lisiur** [comment]
#68
