### ISSUE TITLE
[Bug]: Longer chats not showing

### ISSUE THREAD

**Issue by xyana** [lisiur/ChatWizard#64]
### Describe the bug

Longer chats not showing

### Steps to Reproduce

1. have a long chat going. In chromium.
2. Close chatwizard
3. close the browser tab
4. re-start the application and reload the webpage 
5. click on a chat

### Expected behavior

Should show the previous chat content

### App Info

 - App Version: 0.6.0
 - Platform: linux
 - OS Type: Linux
 - OS Version: 22.04
 - OS Arch: x86_64

### Additional context

One odd workaround is that if you triple click the conversation is does load.

**Comment by lisiur** [comment]
Thank you for your feedback, but I'm confused about a few things:

1. Did you use the web server in the desktop version or the chat-wizard-server directly?
2. Were there any messages replying when you closed the application?
3. When you said the previous chat content should be displayed, do you mean the content was lost, or the conversation content did not reload?

It would be great if you could explain it with a video.

**Comment by xyana** [comment]
1. web-server in the desktop version
2. nothing was being replied when I closed the chat
3. content is still there just not displayed

Video is a bit hard because I'm working on some copy writing and have to blur the content. 


So when I get back to the chat it's empty like this:

![Screenshot from 2023-09-06 08-19-02](https://github.com/lisiur/ChatWizard/assets/17763906/491cc95c-37b6-4311-a15a-55faf95488db)

When I keep clicking on the conversation the chat does show up eventually:

![Screenshot from 2023-09-06 08-19-56](https://github.com/lisiur/ChatWizard/assets/17763906/67788d74-3f80-4ef4-9e2a-ac37ef155acd)

So the data is clearly there.

These are the errors in de web developer console:
[chat-wizard-error-log.log](https://github.com/lisiur/ChatWizard/files/12534103/chat-wizard-error-log.log)

This is one of the errors:

```
index-435f78c4.js:1136 Uncaught (in promise) Error: getVersion not supported in web
    at F3 (index-435f78c4.js:1136:4824)
    at Index-a75632c7.js:125:13006
F3 @ index-435f78c4.js:1136
(anonymous) @ Index-a75632c7.js:125
Promise.then (async)
(anonymous) @ Index-a75632c7.js:125
index-435f78c4.js:1136 Uncaught (in promise) Error: checkUpdate not supported in web
    at z3 (index-435f78c4.js:1136:4924)
    at Index-a75632c7.js:125:13052
z3 @ index-435f78c4.js:1136
(anonymous) @ Index-a75632c7.js:125
Promise.then (async)
(anonymous) @ Index-a75632c7.js:125
Chat-a6487541.js:155 Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at ye (Chat-a6487541.js:155:15623)
    at Chat-a6487541.js:155:16735
ye @ Chat-a6487541.js:155
(anonymous) @ Chat-a6487541.js:155
setTimeout (async)
D.N.immediate @ Chat-a6487541.js:155
Go @ index-435f78c4.js:1
Jt @ index-435f78c4.js:1
C @ index-435f78c4.js:1
ps @ index-435f78c4.js:1
bt @ index-435f78c4.js:1
D @ Chat-a6487541.js:155
(anonymous) @ Chat-a6487541.js:155
setTimeout (async)
N.immediate @ Chat-a6487541.js:155
Go @ index-435f78c4.js:1
Jt @ index-435f78c4.js:1
C @ index-435f78c4.js:1
Go @ index-435f78c4.js:1
wf @ index-435f78c4.js:1
Promise.then (async)
xf @ index-435f78c4.js:1
hs @ index-435f78c4.js:1
b @ index-435f78c4.js:1
gc @ index-435f78c4.js:1
pl @ index-435f78c4.js:1
$o @ index-435f78c4.js:1
(anonymous) @ index-435f78c4.js:1
e.<computed> @ index-435f78c4.js:1
addPreviousLogs @ chat-5d2f8ca2.js:1
loadPrevLogs @ chat-5d2f8ca2.js:1
await in loadPrevLogs (async)
(anonymous) @ Chat-a6487541.js:155
c @ chat-5d2f8ca2.js:1
f @ chat-5d2f8ca2.js:1
(anonymous) @ chat-5d2f8ca2.js:1
```

**Comment by lisiur** [comment]
Thanks for your feedback，will be fixed in next release.
