### ISSUE TITLE
[Feature]: mlc chat compatibility

### ISSUE THREAD

**Issue by koalaeagle** [lisiur/ChatWizard#65]
### Is your feature request related to a problem? Please describe.

Currently ChatWizard does not appear to work with mlc chat's OpenAI compatible rest API: https://mlc.ai/mlc-llm/docs/deploy/rest.html

The chat hangs, similar to what was happening here: https://github.com/lisiur/ChatWizard/issues/56

Unfortunately, mlc chat does not appear to have logging that I can easily enable, however, I have looked at a sample POST request sent by ChatWizard with wireshark. If I send a similar request via curl I get a response as expected, so I am not sure exactly why the response isn't showing via ChatWizard.

Sample working curl request:

```
curl -X POST "http://127.0.0.1:8080/v1/chat/completions" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"model": "some_model_name", "messages": [{"role": "user", "content": "Write a haiku"}], "stream": "True"}'
data: {"choices":[{"index":0,"delta":{"role":"assistant","content":"Sun sets"},"finish_reason":"stop"}]}

data: {"choices":[{"index":0,"delta":{"role":"assistant","content":" slowly"},"finish_reason":"stop"}]}

data: {"choices":[{"index":0,"delta":{"role":"assistant","content":" down"},"finish_reason":"stop"}]}
```

The output continues streaming.

Following the stream of a request sent by ChatWizard (via wireshark), I see similar results. However, the returned stream does not appear in the ChatWizard client.

I am using version 0.6.0 on an m1 macbook.

### Describe the solution you'd like

Is it possible make ChatWizard compatible with mlc chat in a similar way to what was done with LocalAI?

### Describe alternatives you've considered

LocalAI is an alternative. However, I have found mlc much easier to run on AMD cards. It also has support for quite a selection of hardware (cpu, gpus, phones, etc).

### Additional context

N/A

**Comment by lisiur** [comment]
Sorry for the late response, I was on holiday these past few days. I think I have figured out what the problem is. I'll fix it as soon as possible.
