### ISSUE TITLE
[Feature]: Increase font size in chats

### ISSUE THREAD

**Issue by undefiened** [lisiur/ChatWizard#66]
### Is your feature request related to a problem? Please describe.

Font size is too small on a high-DPI screen in Ubuntu. Or, in general, it is good to have an opportunity to increase font size compared to the default, e.g., if you have bad vision.

### Describe the solution you'd like

A shortcut or a setting to increase the font size

### Describe alternatives you've considered

It looks like there is an upstream issue with tauri that it doesn't support zoom feature - https://github.com/tauri-apps/tauri/issues/3310

If the server version is enabled, then I can open the app in a browser, and I can zoom there. However, zoom scales interface disproportionally more compared to the chat text (the interface starts taking too much space even though fonts are still small).

So, I feel like the best option would be to have a setting for font size in chats.

I tried searching by "font" or "size", but I can't find any quick way to change the font size in the code.

### Additional context

-

**Comment by undefiened** [comment]
As a workaround, a custom CSS style can be used in browsers (for example, using the "Stylish" extension in Firefox)

```
.grid.gap-4.pb-6 div {
    font-size: 24px;
}
```

**Comment by lisiur** [comment]
![CleanShot 2023-11-13 at 11 12 46](https://github.com/lisiur/ChatWizard/assets/15188817/548113dc-a352-4e9d-a252-7808b41891e9)

**Comment by undefiened** [comment]
Looks great, thank you very much!
