### ISSUE TITLE
[Bug]: UUID Parsing error when using GPT 4 Turbo

### ISSUE THREAD

**Issue by Timtendo12** [lisiur/ChatWizard#71]
### Describe the bug

Whenever I try to chat using the "gpt-4-turbo" model it returns the same error.

### Steps to Reproduce

1. Go to model
2. Add a new model "gpt-4-turbo"
3. Create a new chat
4. Send a message and the error appears.

### Expected behavior

I expect the chat to generate an answer.

### App Info

I dont have an "about page"

![image](https://github.com/lisiur/ChatWizard/assets/41442518/0cb104ed-1eef-48cc-a1a6-67466528c563)

![image](https://github.com/lisiur/ChatWizard/assets/41442518/4ea24a66-492c-46b7-9969-24d40b34639b)

### Additional context

Screenshot:

![image](https://github.com/lisiur/ChatWizard/assets/41442518/d6e8d8a6-4a54-4260-8124-b8ce57c4bf09)

**Comment by lisiur** [comment]
I'm sorry, I don't have the key for gpt-4 and cannot replicate this issue.

**Comment by Timtendo12** [comment]
> I'm sorry, I don't have the key for gpt-4 and cannot replicate this issue.

I can confirm that the issue fixed itself. Best fix for now is to just create a new chat. I also can't explain exactly what happend.
